// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mainmodule.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class RetrieveObjectByGUID extends CustomJavaAction<IMendixObject>
{
	private java.lang.String guidParm;
	private java.lang.String entityToReturn;

	public RetrieveObjectByGUID(IContext context, java.lang.String guidParm, java.lang.String entityToReturn)
	{
		super(context);
		this.guidParm = guidParm;
		this.entityToReturn = entityToReturn;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Core.retrieveId(getContext(), Core.createMendixIdentifier(guidParm));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RetrieveObjectByGUID";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
